In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
width = 9
height = 9
n_mines = 10

In [7]:
stage = np.zeros((width, height, 3), dtype='int8')

In [193]:
def get_init_stage(width=9, height=9, n_mines=10):
    # set stage
    stage = np.zeros((width, height, 3), dtype='int8')
    # assign mines
    selected_long = np.zeros((width * height), dtype='bool')
    selected_long[np.random.choice(range(0, width * height), n_mines, replace=False)] = True
    selected = selected_long.reshape((width, height))
    stage[selected, 1] = 1
    # set neighbour mine counts
    mines_padded = np.zeros((width + 2, height + 2), dtype='int8')
    mines_padded[1:-1, 1:-1] = stage[:, :, 1]
    for x in range(width):
        for y in range(height):
            if stage[x, y, 1] == 0:
                stage[x, y, 2] = np.sum(mines_padded[x: x + 3, y: y + 3])
    return stage          

In [194]:
def print_stage(stage):
    return stage[:, :, 2] - stage[:, :, 1]

In [195]:
print_stage(get_init_stage())

array([[ 0,  0,  0,  0,  0,  1, -1,  1,  0],
       [ 1,  1,  1,  0,  0,  1,  2,  2,  1],
       [ 1, -1,  1,  0,  0,  0,  1, -1,  1],
       [ 1,  2,  3,  2,  1,  0,  1,  1,  1],
       [ 0,  1, -1, -1,  1,  0,  0,  0,  0],
       [ 0,  1,  2,  2,  1,  0,  1,  1,  1],
       [ 0,  0,  1,  1,  1,  0,  2, -1,  2],
       [ 0,  1,  3, -1,  2,  0,  2, -1,  2],
       [ 0,  1, -1, -1,  2,  0,  1,  1,  1]], dtype=int8)

In [196]:
def show_visible(stage):
    return stage[:, :, 0] * print_stage(stage)

In [197]:
show_visible(get_init_stage())

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int8)

In [198]:
def step_on(stage, coord):
    stage[coord[0], coord[1], 0] = 1
    # if not mine, expand all (directly) neighbouring non-mine tiles
    return stage

In [211]:
temp_stage = get_init_stage()

In [212]:
temp_printed = print_stage(temp_stage)
temp_printed

array([[ 0,  1,  1,  1,  0,  0,  0,  0,  0],
       [ 0,  1, -1,  1,  0,  0,  0,  0,  0],
       [ 1,  2,  1,  1,  0,  1,  2,  2,  1],
       [-1,  1,  0,  0,  0,  1, -1, -1,  2],
       [ 1,  1,  1,  2,  3,  4,  5, -1,  2],
       [ 0,  0,  1, -1, -1, -1, -1,  2,  1],
       [ 0,  0,  1,  2,  3,  3,  2,  1,  0],
       [ 0,  0,  0,  0,  0,  1,  1,  1,  0],
       [ 0,  0,  0,  0,  0,  1, -1,  1,  0]], dtype=int8)

In [213]:
temp_printed[5, 3]

-1

In [214]:
show_visible(temp_stage)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int8)

In [218]:
temp_after = step_on(temp_stage, (5, 3))
show_visible(temp_after)

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, -1,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0]], dtype=int8)

In [219]:
def is_dead(stage):
    return np.sum(show_visible(stage) < 0)

In [220]:
is_dead(temp_after)

1